
name: Build

on:
  push:
    branches: [ "main", "dev/*" ]
  pull_request:
    branches: [ "main", "dev/*" ]


jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]

    env:
      Configuration: ${{ matrix.configuration }}
      Platform: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: SHA
      id: sha
      run: echo "sha=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_OUTPUT

    - name: Build
      run: |
        $sha = "${{ steps.sha.outputs.sha }}"
        New-Item -Path "build/Starward/" -Type Directory
        msbuild src/Starward.Launcher "-property:Configuration=$env:Configuration;Platform=$env:Platform;OutDir=$(Resolve-Path "build/Starward/")"
        dotnet publish src/Starward -c $env:Configuration -o "build/Starward/app-build.$sha" -p:Platform=$env:Platform -p:Version="0.0.1-build.$sha" -p:DefineConstants=CI -p:PublishTrimmed=true -p:TrimMode=partial
        Add-Content "build/Starward/version.ini" -Value "app_folder=app-build.$sha`r`nexe_name=Starward.exe"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Starward_${{ matrix.configuration }}_${{ matrix.platform }}_${{ steps.sha.outputs.sha }}
        path: build/Starward/
