
name: Build Localization

on:
  push:
    branches: [ "l10n/main" ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: |
        dotnet publish Starward.Core -c Release -o build
        dotnet publish Starward.Language -c Release -o build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build
        path: build

