
name: Upload Metadata

on:
  push:
    branches: [ "metadata" ]

jobs:

  upload:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Upload to OSS
      run: |
        rm -rf ./.git ./.github
        curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
        ossutil config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.ACCESS_KEY_ID }} -k ${{ secrets.ACCESS_KEY_SECRET }}
        ossutil cp -rf ./ oss://starward/metadata/

